services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fibertime-net

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fibertime-net

  # fibertime-fe:
  #   build:
  #     context: ./fibertime_fe
  #     dockerfile: ./Dockerfile.dev
  #   volumes:
  #     - ./fibertime_fe:/app:ro
  #     - ./fibertime_fe/package-lock.json:/app/package-lock.json
  #     - fe-next:/app/.next
  #     - fe-modules:/app/node_modules
  #   networks:
  #     - fibertime-net

  # fibertime-be:
  #   build:
  #     context: ./fibertime_be
  #     dockerfile: ./Dockerfile.dev
  #   environment:
  #     - DB_HOST=fibertime-db
  #     - DB_PORT=5432
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=root
  #     - DB_NAME=fibertime
  #     - REDIS_URL=redis://redis:6379
  #     - JWT_SECRET=fibertime-practical-haha-secret-me
  #     - PORT=5588
  #     - FRONTEND_URL=http://localhost:3535
  #     - OTP_EXPIRY_MINUTES=5
  #     - DEVICE_CODE_EXPIRY_MINUTES=5
  #   volumes:
  #     - ./fibertime_be:/app
  #     - be-modules:/app/node_modules
  #   ports:
  #     - "5588:5588"
  #   depends_on:
  #     - fibertime-db
  #     - redis
  #   networks:
  #     - fibertime-net

  fibertime-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fibertime
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - fibertime-db:/var/lib/postgresql/data/pgdata
    networks:
      - fibertime-net

networks:
  fibertime-net:
volumes:
  fibertime-db:
  fe-modules:
  fe-next:
  be-modules:
