services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fibertime-net

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fibertime-net

  fibertime-fe:
    build:
      context: ./fibertime_fe
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=/api
    ports:
      - "3535:3535"
    networks:
      - fibertime-net

  fibertime-be:
    build:
      context: ./fibertime_be
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - DB_HOST=fibertime-db
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=fibertime
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=fibertime-practical-haha-secret-me
      - PORT=5588
      - FRONTEND_URL=http://localhost:3535
      - OTP_EXPIRY_MINUTES=5
      - DEVICE_CODE_EXPIRY_MINUTES=24
      - BUNDLE_EXPIRY_DAYS=30
      - ALLOW_CREDENTIALS=true
    ports:
      - "5588:5588"
    # extra_hosts:
    # - "fibertime-be:127.0.0.1"
    networks:
      - fibertime-net

  fibertime-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fibertime
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - fibertime-db:/var/lib/postgresql/data/pgdata
    networks:
      - fibertime-net

networks:
  fibertime-net:
volumes:
  fibertime-db:
  fe-modules:
  fe-next:
  be-modules:
  redis-data: